apiVersion: v1
kind: Service
metadata:
  name: go-network
  labels:
    app: go-network
spec:
  selector:
    app: go-network
  ports:
    - name: dws-server
      port: 8000
      targetPort: dws-device
    - name: plc-server
      port: 5001
      targetPort: plc-device
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-network
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-network
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: go-network
    spec:
      containers:
        - name: nacos
          resources:
            requests:
              memory: "32Mi"
              cpu: "125m"
            limits:
              memory: "64Mi"
              cpu: "250m"
          imagePullPolicy: IfNotPresent
          image: darvik80/go-network:latest
          ports:
            - containerPort: 8000
              name: dws-device
            - containerPort: 5000
              name: plc-device
          volumeMounts:
            - name: podinfo
              mountPath: /etc/podinfo
      volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations