apiVersion: v1
kind: Service
metadata:
  name: nacos
  labels:
    app: nacos
spec:
  selector:
    app: nacos
  ports:
    - port: 8848
      name: nacos
      targetPort: 8848
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos
spec:
  selector:
    matchLabels:
      app: nacos
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nacos
    spec:
      containers:
        - name: nacos
          imagePullPolicy: IfNotPresent
          image: nacos/nacos-server
          ports:
            - containerPort: 8848
              name: nacos
          env:
            - name: PREFER_HOST_MODE
              value: hostname
            - name: MODE
              value: standalone
            - name: JAVA_OPT_EXT
              value: "-Xms512m -Xmx512m -Xmn128m -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=128m"
